check50:
  files: &check50_files
    - !exclude '*.pyc'
    - !exclude '__pycache__'
    - !require application.py
    - !require templates/layout.html
    - !require templates/form.html
    - !require templates/error.html
    - !require static/styles.css
  dependencies:
    - "git+https://github.com/jelleas/uva_check50.git#egg=uva.check50>=0.0.4"

submit50:
  files: *check50_files
