check50:
  files: &check50_files
    - !exclude "*"
    - !include "*.c"
    - !include "*.h"
    - !include "*.md"
    - !exclude speller.c
    - !require dictionary.c
    - !require dictionary.h
submit50:
  files: *check50_files
