check50:
  files: &check50_files
    - !exclude "*"
    - !include "find.c"
    - !include "generate.c"
    - !include "helpers.h"
    - !include "Makefile"
    - !require "helpers.c"

submit50:
  files: *check50_files
