check50:
  dependencies:
    - flask_session
    - cs50>=5.0.2
  files: &check50_files
    - !exclude "*.pyc"
    - !exclude __pycache__
    - !require application.py
    - !require finance.db
    - !require helpers.py

submit50:
  files: *check50_files
