check50:
  files: &check50_files
    - !exclude "*"
    - !require "Makefile"
    - !require "tiles.c"
    - !require "helpers.c"
    - !require "helpers.h"
    - !require "board.h"

submit50:
  files: *check50_files
