name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  yaml_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v1
        with:
          config_data: "{extends: relaxed, rules: {}}"
